### ISSUE TITLE
error: uncaughtException: buffer.toJSON(...).map is not a function

### ISSUE THREAD

**Issue by lifubang** [GangLuICT/RMQ-Client4Nodejs#1]
error: uncaughtException: buffer.toJSON(...).map is not a function
日志如下：
麻烦帮忙看看是什么错误？
17:48:10.059 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
17:48:10.065 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
17:48:10.071 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
17:48:10.071 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
17:48:10.071 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
17:48:10.071 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - Platform: Windows
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
17:48:10.072 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
17:48:10.073 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
17:48:10.073 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\lifubang\AppData\Local\Temp (java.io.tmpdir)
17:48:10.073 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
17:48:10.073 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
17:48:10.085 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
17:48:10.085 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
17:48:10.291 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x7194e1ff2057b3d0 (took 8 ms)
17:48:10.308 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
17:48:10.308 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
17:48:11.365 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
17:48:11.369 [NettyClientWorkerThread_2] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
17:48:11.438 [NettyClientSelector_1] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
2016-06-28T09:48:11.525Z - **# error: uncaughtException: buffer.toJSON(...).map is not a function** date=Tue Jun 28 2016 17:48:11 GMT+0800 (中国标准时间), pid=8832, uid=null, gid=null, cwd=d:\Deploy\ACMcoderExam, execPath=D:\nodejs\node.exe, version=v6.0.0, argv=[D:\nodejs\node.exe, d:\Deploy\ACMcoderExam\bin\www.js], rss=154804224, heapTotal=85274624, heapUsed=54232520, loadavg=[0, 0, 0], uptime=31297.0261742, trace=[column=59, file=D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\MQMessage.js, function=new MQMessage, line=32, method=null, native=false, column=17, file=D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\test\Producer.js, function=null, line=29, method=null, native=false, column=17, file=D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\MQProducer.js, function=MQProducer.init, line=60, method=init, native=false, column=10, file=D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\test\Producer.js, function=, line=27, method=null, native=false, column=32, file=module.js, function=Module._compile, line=541, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=550, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=456, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=415, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=407, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=466, method=require, native=false], stack=[TypeError: buffer.toJSON(...).map is not a function,     at new MQMessage (D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\MQMessage.js:32:59),     at D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\test\Producer.js:29:17,     at MQProducer.init (D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\MQProducer.js:60:17),     at Object.<anonymous> (D:\Deploy\ACMcoderExam\RMQ-Client4Nodejs\test\Producer.js:27:10),     at Module._compile (module.js:541:32),     at Object.Module._extensions..js (module.js:550:10),     at Module.load (module.js:456:32),     at tryModuleLoad (module.js:415:12),     at Function.Module._load (module.js:407:3),     at Module.require (module.js:466:17)]

**Comment by lifubang** [comment]
Have fixed it.
#2
